import type { Metadata } from "next";
import { gothic } from "./ui/fonts";
import AvenueLogo from "./ui/components/avenue-marble-logo";
import NavBar from "./ui/navbar/navbar";
import "./globals.css";
import Footer from "./ui/components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${gothic.className} subpixel-antialiased text-almostblack flex flex-col`}
      >
        <div className="flex justify-center">
          <AvenueLogo />
        </div>
        <div className="flex w-full justify-center">
          <div className="flex w-full 2xl:w-3/4 my-12">
            <NavBar />
          </div>
        </div>
        {children}
        <div className="flex justify-center w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}
