import type { Metadata } from "next";
import { gothic } from "./ui/fonts";
import AvenueLogo from "./ui/avenue-marble-logo";
import NavBar from "./ui/navbar/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${gothic.className} subpixel-antialiased`}>
        <div className="flex justify-center pt-12 pl-12 pr-12">
          <AvenueLogo />
        </div>
        <div className="flex justify-center">
          <NavBar />
        </div>
        {children}
      </body>
    </html>
  );
}
